name: Lint Code Base

on:
  push:
    branches: ["hyde-gallery"]
  pull_request:
    branches: ["hyde-gallery"]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_PYTHON_PYLINT: true
          VALIDATE_PYTHON_MYPY: false
          VALIDATE_PYTHON_PYINK: false
          VALIDATE_PYTHON_RUFF: false
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_JSON: true
          FIX_PYTHON_BLACK: true
          DEFAULT_BRANCH: "hyde-gallery"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x" # Specify the Python version you need

      - name: Run generate_readme.py
        run: python generate_readme.py # Run the script from the root directory

      - name: Commit changes
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add .  # Specify the README file or use . for all changes
          git commit -m "Update README from GitHub Actions" || echo "No changes to commit"
